packages:
  - web

ignoredBuiltDependencies:
  - esbuild
  - puppeteer
  - re2

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - unrs-resolver

overrides:
  hono@<4.11.10: '>=4.11.10'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.1: '>=10.2.1'
